# This file sets what settings in agile.par are read as compile
# time flags and whether they should affect the build hash.
# [components] is for hidden implied options inferred by the precompiler

[components]
[components.source_dt]
type = "flag"
name = "SOURCE_DT"
flags = ["fypp", "hash"]
default = false

[components.source_compact]
type = "flag"
name = "SOURCE_COMPACT"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_dt"]

[components.source_nonlocal]
type = "flag"
name = "SOURCE_NONLOCAL"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_dt"]

[components.source_nonlocal_full]
type = "flag"
name = "SOURCE_NONLOCAL_FULL"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_dt"]

[components.source_local]
type = "flag"
name = "SOURCE_LOCAL"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_dt"]

[methodlist]
[methodlist.phys]
type = "option"
name = "PHYS"
options = ["hd", "mhd", "ffhd", "srhd"]
flags = ["fypp", "hash"]
default = "hd"

[methodlist.flux_adaptive_diffusion]
type = "flag"
name = "FLUX_AD"
flags = ["fypp", "hash"]
default = false

[boundlist]
[boundlist.specialboundary]
type = "flag"
name = "SPECIALBOUNDARY"
flags = ["fypp", "hash"]
default = false

[hd_list]
[hd_list.hd_gravity]
type = "flag"
name = "GRAVITY"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[hd_list.hd_n_tracer]
type = "value"
name = "N_TRACER"
dtype = "int"
flags = ["fypp", "hash"]

[hd_list.hd_radiative_cooling]
type = "flag"
name = "COOLING"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[ffhd_list]
[ffhd_list.ffhd_pdivb]
type = "flag"
name = "PDIVB"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_nonlocal"]

[ffhd_list.ffhd_hyperbolic_thermal_conduction]
type = "flag"
name = "HYPERTC"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_nonlocal"]

[ffhd_list.ffhd_hyperbolic_thermal_conduction_anisotropic]
type = "flag"
name = "HYPERTC_ANISO"
flags = ["fypp", "hash"]
default = false
implies = ["ffhd_list.ffhd_hyperbolic_thermal_conduction"]

[ffhd_list.ffhd_gravity]
type = "flag"
name = "GRAVITY"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[ffhd_list.ffhd_radiative_cooling]
type = "flag"
name = "COOLING"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[ffhd_list.ffhd_source_usr]
type = "flag"
name = "SOURCE_USR"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[ffhd_list.ffhd_energy_only]
type = "flag"
name = "FFHD_ENERGY_ONLY"
flags = ["fypp", "hash"]
default = false

[mhd_list]
[mhd_list.mhd_gravity]
type = "flag"
name = "GRAVITY"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[mhd_list.mhd_n_tracer]
type = "value"
name = "N_TRACER"
dtype = "int"
flags = ["fypp", "hash"]

[mhd_list.mhd_source_usr]
type = "flag"
name = "SOURCE_USR"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[mhd_list.mhd_resistivity]
type = "flag"
name = "RESISTIVE"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_compact"]

[mhd_list.mhd_radiative_cooling]
type = "flag"
name = "COOLING"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[mhd_list.mhd_hyperbolic_thermal_conduction]
type = "flag"
name = "HYPERTC"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_nonlocal"]

[mhd_list.mhd_hyperbolic_thermal_conduction_anisotropic]
type = "flag"
name = "HYPERTC_ANISO"
flags = ["fypp", "hash"]
default = false
implies = ["mhd_list.mhd_hyperbolic_thermal_conduction", "components.source_nonlocal_full"]

[mhd_list.mhd_energy_only]
type = "flag"
name = "MHD_ENERGY_ONLY"
flags = ["fypp", "hash"]
default = false

[srhd_list]
[srhd_list.srhd_source_usr]
type = "flag"
name = "SOURCE_USR"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[srhd_list.srhd_n_tracer]
type = "value"
name = "N_TRACER"
dtype = "int"
flags = ["fypp", "hash"]

[meshlist]
[meshlist.refine_usr]
type = "flag"
name = "REFINE_USR"
flags = ["fypp", "hash"]
default = false
