# This file sets what settings in amrvac.par are read as compile
# time flags and whether they should affect the build hash.
# [components] is for hidden implied options inferred by the precompiler

[components.source_term]
type = "flag"
name = "SOURCE_TERM"
flags = ["fypp", "hash"]
default = false

[components.source_nonlocal]
type = "flag"
name = "SOURCE_NONLOCAL"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_term"]

[components.source_local]
type = "flag"
name = "SOURCE_LOCAL"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_term"]

[methodlist]
[methodlist.phys]
type = "option"
name = "PHYS"
options = ["hd", "mhd", "ffhd"]
flags = ["fypp", "hash"]
default = "hd"

[phys_list]
[phys_list.gravity]
type = "flag"
name = "GRAVITY"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[phys_list.hyperbolic_thermal_conduction]
type = "flag"
name = "HYPERTC"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_nonlocal"]

[phys_list.radiative_cooling]
type = "flag"
name = "COOLING"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_local"]

[phys_list.source_usr]
type = "flag"
name = "SOURCE_USR"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_term"]