# This file sets what settings in amrvac.par are read as compile
# time flags and whether they should affect the build hash.

[components]
[components.source_term]
type = "flag"
name = "SOURCE_TERM"
flags = ["fypp"]
default = false

[components.cooling]
type = "flag"
name = "COOLING"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_term"]

[components.gravity]
type = "flag"
name = "GRAVITY"
flags = ["fypp", "hash"]
default = false
implies = ["components.source_term"]

[components.bfield]
type = "flag"
name = "BFIELD"
flags = ["fypp", "hash"]
default = false

[components.usr_source]
type = "flag"
name = "USR_SOURCE"
flags = ["fypp", "hash"]
default = false

[methodlist]
[methodlist.phys]
type = "option"
name = "PHYS"
options = ["hd", "mhd", "ffhd"]
flags = ["fypp", "hash"]
default = "hd"
