name: tests (GPU)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nvidia:
    name: NVIDIA GPU
    env:
      AGILE_DIR: ${{ github.workspace }}
      
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6

      - name: set paths
        run: |
          echo "/volume1/scratch/shared_software/openmpi-nvhpc-5.0.8/bin" >> "$GITHUB_PATH"
          echo "/volume1/scratch/shared_software/nvhpc/hpc_sdk/Linux_x86_64/25.11/compilers/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: list GPUs
        run: nvidia-smi

      - name: check compiler versions
        run: |
          mpirun --version
          nvfortran --version

      - name: create Python environment
        run: |
          python3.13 -m pip install uv
          uv sync

      - name: compile and run tests (OpenACC mode)
        run: |
          cd tests
          NUM_PROCS=2 arch=nvidia OPENACC=1 ./test_runner.sh

      - name: compile and run tests (OpenMP mode)
        run: |
          cd tests
          NUM_PROCS=2 arch=nvidia OPENMP=1 ./test_runner.sh
