name: tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  GNU:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        FC_compiler: [gfortran-12]
        CC_compiler: [gcc-12]
        suite: [hd]

    env:
      CC: ${{ matrix.CC_compiler }}
      FC: ${{ matrix.FC_compiler }}
      AMRVAC_DIR: ${{ github.workspace }}
      GCC_PACKAGE_NAME: gcc@12

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} / ${{ matrix.FC_compiler }} / ${{ matrix.suite }}

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          if [[ $RUNNER_OS == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install ${{ matrix.FC_compiler }}
            sudo apt-get install openmpi-bin libopenmpi-dev
          else
            brew install ${{ env.GCC_PACKAGE_NAME }}
            brew install open-mpi
            brew install grep
            ln -s $(which ${{ matrix.FC_compiler }}) /usr/local/bin/gfortran
          fi
      - name: check compiler versions
        run: |
          ${FC} --version
          ${CC} --version
          mpirun --version
      - name: create Python environment
        run: |
          pip install uv
          uv sync
      - name: compile and run tests
        run: |
          cd tests
          ARCH=gnu ./test_runner.sh ${{ matrix.suite }}

  INTEL:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        suite: [hd]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / ifx / ${{ matrix.suite }}

    env:
      FC: ifx
      CC: icc
      AMRVAC_DIR: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2
      - name: setup for Intel oneAPI
        # see https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository  -y "deb https://apt.repos.intel.com/oneapi all main"
      - name: install Intel oneAPI
        run: |
          sudo apt update 
          sudo apt-get install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
          sudo apt-get install intel-oneapi-compiler-fortran
          sudo apt-get install intel-oneapi-mpi
          sudo apt-get install intel-oneapi-mpi-devel
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
      - name: check compiler versions
        run: |
          ${FC} --version
          mpirun --version
          mpiifx --version
      - name: create Python environment
        run: |
          pip install uv
          uv sync
      - name: compile
        run: |
          cd tests
          ARCH=ifx ./test_runner.sh ${{ matrix.suite }}
